#version: "3.9"
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/dockerApp
      - ./media:/dockerApp/media
    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:14

    #restart: always
    #restart: unless-stopped

    #environment:
    #  POSTGRES_DB: ...
    #  POSTGRES_USER: ...
    #  POSTGRES_PASSWORD: ...
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}

    # ports:
    #  - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data   

volumes:
  postgres_data: