# Generated by Django 5.0.2 on 2026-07-05 04:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('ordinal', models.IntegerField()),
            ],
            options={
                'db_table': 'portfolio_category',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Место работы')),
                ('spec', models.CharField(max_length=255, verbose_name='Должность')),
                ('years', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(verbose_name='Обязанности')),
                ('progress', models.TextField(verbose_name='Достижения')),
                ('doc', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файлы')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Конец работы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('ordinal', models.IntegerField()),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webApp.category', verbose_name='Категории')),
            ],
            options={
                'db_table': 'portfolio_place',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Конец работы')),
                ('location', models.CharField(max_length=255, verbose_name='Место работы')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специальность')),
                ('responsibilities', models.CharField(blank=True, max_length=500, null=True, verbose_name='Обязанности')),
                ('progress', models.CharField(max_length=500, verbose_name='Достижения')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webApp.category', verbose_name='Категории')),
            ],
            options={
                'db_table': 'portfolio_portfolio',
            },
        ),
    ]
